name: root_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - scipy
  - tensorflow
  - matplotlib
  - seaborn
  - root
  - scikit-learn
  - pandas
  - awkward
  - pip
  - vim
  - xrootd  
  - pip:
      - uproot
      - fsspec-xrootd
